name: binder-environment
channels:
  - conda-forge
dependencies:
  - python=3.8
  - basemap
  - pandas==1.5.3
  - pip
  - pip:
    - git+https://github.com/morphomatics/morphomatics.git@v3.0#egg=morphomatics
    - scikit-learn==1.0
    - matplotlib==3.5
    - ipywidgets
